# Generated by Django 5.2.17 on 2026-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draft_id", models.CharField(max_length=64)),
                ("mandate_id", models.CharField(blank=True, max_length=64)),
                ("scenario_id", models.CharField(max_length=16)),
                ("instruction", models.TextField()),
                ("guidance", models.JSONField(default=list)),
                ("status", models.CharField(default="draft", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.BigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("edited", "edited"),
                            ("activated", "activated"),
                            ("deactivated", "deactivated"),
                            ("deleted", "deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=64, unique=True)),
                ("scenario_id", models.CharField(max_length=16)),
                ("mandate_id", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_status", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api", "API / try page"),
                            ("offline", "Offline replay"),
                            ("live", "Live Leash run"),
                        ],
                        default="api",
                        max_length=8,
                    ),
                ),
                ("run_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("authorization_id", models.CharField(db_index=True, max_length=64)),
                (
                    "source_authorization_id",
                    models.CharField(blank=True, max_length=64),
                ),
                ("scenario_id", models.CharField(blank=True, max_length=16)),
                ("card_id", models.CharField(blank=True, db_index=True, max_length=32)),
                ("merchant_id", models.CharField(blank=True, max_length=32)),
                ("merchant_name", models.CharField(blank=True, max_length=128)),
                (
                    "amount_chf",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("sim_timestamp", models.DateTimeField(db_index=True, null=True)),
                ("query", models.JSONField()),
                ("state", models.JSONField(default=dict)),
                ("policies_snapshot", models.JSONField(default=list)),
                ("p_approved", models.FloatField(null=True)),
                ("p_rejected", models.FloatField(null=True)),
                ("p_review", models.FloatField(null=True)),
                ("confidence", models.FloatField(null=True)),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("review_needed", "Review needed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "approve"),
                            ("decline", "decline"),
                            ("step_up", "step_up"),
                        ],
                        max_length=8,
                    ),
                ),
                ("policy_scores", models.JSONField(default=list)),
                ("reason", models.TextField(blank=True)),
                ("jev_model", models.CharField(blank=True, max_length=32)),
                ("jev_usage", models.JSONField(default=dict)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("posted", models.BooleanField(default=False)),
                ("post_status", models.CharField(blank=True, max_length=255)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[("approve", "approve"), ("decline", "decline")],
                        max_length=8,
                    ),
                ),
                ("resolved_at", models.DateTimeField(null=True)),
                ("resolve_status", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "authorization_id"),
                        name="one_evaluation_per_run_authorization",
                    )
                ],
            },
        ),
    ]
